export const GET_MEN_PRODUCT_REQUEST = "GET_MEN_PRODUCT_REQUEST";
export const GET_MEN_PRODUCT_SUCCESS = "GET_MEN_PRODUCT_SUCCESS";
export const GET_MEN_PRODUCT_FAILURE = "GET_MEN_PRODUCT_FAILURE";

export const GET_WOMEN_PRODUCT_REQUEST = "GET_WOMEN_PRODUCT_REQUEST";
export const GET_WOMEN_PRODUCT_SUCCESS = "GET_WOMEN_PRODUCT_SUCCESS";
export const GET_WOMEN_PRODUCT_FAILURE = "GET_WOMEN_PRODUCT_FAILURE";

export const GET_CHILD_PRODUCT_REQUEST = "GET_CHILD_PRODUCT_REQUEST";
export const GET_CHILD_PRODUCT_SUCCESS = "GET_CHILD_PRODUCT_SUCCESS";
export const GET_CHILD_PRODUCT_FAILURE = "GET_CHILD_PRODUCT_FAILURE";

export const ADD_MEN_PRODUCT_REQUEST = "ADD_MEN_PRODUCT_REQUEST";
export const ADD_MEN_PRODUCT_SUCCESS = "ADD_MEN_PRODUCT_SUCCESS";
export const ADD_MEN_PRODUCT_FAILURE = "ADD_MEN_PRODUCT_FAILURE";

export const ADD_WOMEN_PRODUCT_REQUEST = "ADD_WOMEN_PRODUCT_REQUEST";
export const ADD_WOMEN_PRODUCT_SUCCESS = "ADD_WOMEN_PRODUCT_SUCCESS";
export const ADD_WOMEN_PRODUCT_FAILURE = "ADD_WOMEN_PRODUCT_FAILURE";

export const ADD_CHILD_PRODUCT_REQUEST = "ADD_CHILD_PRODUCT_REQUEST";
export const ADD_CHILD_PRODUCT_SUCCESS = "ADD_CHILD_PRODUCT_SUCCESS";
export const ADD_CHILD_PRODUCT_FAILURE = "ADD_CHILD_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const GET_USERLIST_REQUEST = "GET_USERLIST_REQUEST";
export const GET_USERLIST_SUCCESS = "GET_USERLIST_SUCCESS";
export const GET_USERLIST_FAILURE = "GET_USERLIST_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
